imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
        public: true			

    david63.quickbooks.listener:
        class: david63\quickbooks\event\listener
        tags: [{ name: event.listener }]

    david63.quickbooks.main.controller:
        class: david63\quickbooks\controller\main_controller

    david63.quickbooks.core.functions:
        class: david63\quickbooks\core\functions
